name = "SCF"
uuid = "8ac1c516-41c4-4b25-88c0-3a4497c3b5dd"
version = "1.0.0-DEV"
authors = ["Cristian Sarabia <sarabiacristian01@gmail.com>"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
LinearAlgebra = "1.12.0"
Printf = "1.11.0"
SpecialFunctions = "2.6.1"
StaticArrays = "1.9.16"
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
